using Verifier = EffectiveCSharp.Analyzers.Tests.Helpers.AnalyzerVerifier<EffectiveCSharp.Analyzers.ReplaceStringFormatAnalyzer>;

namespace EffectiveCSharp.Analyzers.Tests;

#pragma warning disable IDE0028 // We cannot simply object creation on TheoryData because we need to convert from object[] to string, the way it is now is cleaner

public class ReplaceStringFormatTests
{
    public static TheoryData<string, string> TestData()
    {
        TheoryData<string> data = new()
        {
            """
            var str = {|ECS0004:string.Format("Hello, {0}!", "world")|};
            """,
            """
            var str = string.Format("Hello, world!", "world");
            """,

            // The code generated by the string interpolation will call a formatting
            // method whose argument is a params array of objects (until .NET 9)
            // The Math.PI property is a double, which is a value type. In order to
            // coerce that double to be an Object for the params, it will be boxed.
            """
            Console.WriteLine($"The value of pi is {Math.PI}");
            """,

            // You should use expressions to convert arguments to strings to avoid
            // the box
            """
            Console.WriteLine($"The value of pi is {Math.PI.ToString()}");
            """,
            """
            Console.WriteLine($"The value of pi is {Math.PI.ToString("F2")}");
            """,
            """
            Console.WriteLine($"The value of pi is {Math.PI:F2}");
            """,
            """
            bool round = false;
            Console.WriteLine($@"The value of pi is {(round ? Math.PI.ToString() : Math.PI.ToString("F2"))}");
            """
        };

        return data.WithReferenceAssemblyGroups();
    }

    [Theory]
    [MemberData(nameof(TestData))]
    public async Task Analyzer(string referenceAssemblyGroup, string source)
    {
        await Verifier.VerifyAnalyzerAsync(
            $$"""
              public class Program
              {
                void Main()
                {
                  {{source}}
                }
              }
              """,
            referenceAssemblyGroup);
    }
}
